#!/usr/bin/env bash
set -Eeuo pipefail

readonly EX_USAGE=64
readonly INSTALL_DIR="${DONHANG_INSTALL_DIR:-/opt/donhang-9chum}"
readonly RELEASES_DIR="${INSTALL_DIR}/releases"
readonly RUNTIME_ENV="${INSTALL_DIR}/runtime.env"
readonly STATE_DIR="${INSTALL_DIR}/state"
readonly CURRENT_SHA_FILE="${STATE_DIR}/current-sha"
readonly CURRENT_BUNDLE_LINK="${INSTALL_DIR}/current"
readonly DEFAULT_BACKUP_DIR="/var/backups/donhang-9chum"
readonly LOCK_FILE="${DONHANG_LOCK_FILE:-/run/lock/donhang-9chum-maintenance.lock}"
readonly OPERATOR_SBIN_DIR="${DONHANG_OPERATOR_SBIN_DIR:-/usr/local/sbin}"
readonly OPERATOR_LIBEXEC_DIR="${DONHANG_OPERATOR_LIBEXEC_DIR:-/usr/local/libexec}"
readonly IMAGE_REPOSITORY="ghcr.io/djoker96/9chum_order"
readonly SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly BUNDLE_DIR="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"
readonly COMPOSE_FILE="${BUNDLE_DIR}/compose.production.yml"
readonly SIGNATURE_SQL="${BUNDLE_DIR}/deploy/postgres/backup-signature.sql"
readonly BACKUP_FUNCTIONS="${SCRIPT_DIR}/backup-functions.sh"

log() {
  printf '%s %s\n' "$(date +'%Y-%m-%dT%H:%M:%S%z')" "$*"
}

fail() {
  log "ERROR: $*" >&2
  exit 1
}

is_valid_sha() {
  [[ ${1:-} =~ ^[0-9a-f]{40}$ ]]
}

validate_sha_or_exit() {
  if ! is_valid_sha "${1:-}"; then
    printf 'Invalid release SHA.\n' >&2
    exit "${EX_USAGE}"
  fi
}

if [[ ${1:-} == "--validate-only" ]]; then
  [[ $# -eq 2 ]] || validate_sha_or_exit ""
  validate_sha_or_exit "$2"
  printf '%s\n' "$2"
  exit 0
fi

[[ $# -eq 1 ]] || validate_sha_or_exit ""
readonly RELEASE_SHA="$1"
validate_sha_or_exit "${RELEASE_SHA}"

[[ $(id -u) -eq 0 ]] || fail "Release script must run as root."
[[ -f ${COMPOSE_FILE} ]] || fail "Bundled Compose file is missing."
[[ -f ${SIGNATURE_SQL} && -f ${BACKUP_FUNCTIONS} ]] \
  || fail "Bundled backup verification assets are missing."
canonical_bundle_dir="$(realpath -e -- "${BUNDLE_DIR}" 2>/dev/null \
  || realpath "${BUNDLE_DIR}")"
canonical_expected_release_dir="$(realpath -e -- "${RELEASES_DIR}/${RELEASE_SHA}" 2>/dev/null \
  || realpath "${RELEASES_DIR}/${RELEASE_SHA}")"
[[ ${canonical_bundle_dir} == "${canonical_expected_release_dir}" ]] \
  || fail "Release runner is outside its immutable SHA bundle."
[[ -f ${RUNTIME_ENV} ]] || fail "Runtime environment is missing."
[[ $(stat -c '%a' "${RUNTIME_ENV}") == "600" ]] || fail "runtime.env must have mode 0600."
[[ $(stat -c '%U' "${RUNTIME_ENV}") == "root" ]] || fail "runtime.env must be owned by root."

install -d -m 0700 -o root -g root "${STATE_DIR}"
install -d -m 0755 -o root -g root "$(dirname "${LOCK_FILE}")"

exec 9>"${LOCK_FILE}"
flock -n 9 || fail "Another release, backup, or restore verification is running."

set -a
# runtime.env is generated by the root-owned bootstrap script and is never user-controlled.
# shellcheck disable=SC1090
source "${RUNTIME_ENV}"
set +a

readonly APP_PORT
readonly POSTGRES_DB
readonly POSTGRES_USER
readonly POSTGRES_MIGRATOR_USER
readonly SMOKE_URL="${SMOKE_URL:-https://donhang.9chum.vn/api/health}"
readonly BACKUP_DIR="${BACKUP_DIR:-${DEFAULT_BACKUP_DIR}}"

[[ ${APP_PORT:-} =~ ^31[0-9]{2}$ ]] || fail "APP_PORT must be in the 3100 range."
(( APP_PORT >= 3101 && APP_PORT <= 3199 )) || fail "APP_PORT must be between 3101 and 3199."
[[ ${POSTGRES_DB:-} =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]] || fail "POSTGRES_DB is invalid."
[[ ${POSTGRES_USER:-} =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]] || fail "POSTGRES_USER is invalid."
[[ ${POSTGRES_MIGRATOR_USER:-} =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]] \
  || fail "POSTGRES_MIGRATOR_USER is invalid."
[[ ${BACKUP_DIR} == /* && ${BACKUP_DIR} != "/" && ${BACKUP_DIR} != *".."* ]] \
  || fail "BACKUP_DIR must be a specific absolute path."
install -d -m 0700 -o root -g root "${BACKUP_DIR}"

compose() {
  APP_IMAGE="${IMAGE_REPOSITORY}:app-${RELEASE_SHA}" \
  OPS_IMAGE="${IMAGE_REPOSITORY}:ops-${RELEASE_SHA}" \
    docker compose \
      --project-name donhang-9chum \
      --env-file "${RUNTIME_ENV}" \
      --file "${COMPOSE_FILE}" \
      "$@"
}

compose_previous() {
  local sha="$1"
  local compose_file="$2"
  shift 2
  APP_IMAGE="${IMAGE_REPOSITORY}:app-${sha}" \
  OPS_IMAGE="${IMAGE_REPOSITORY}:ops-${sha}" \
    docker compose \
      --project-name donhang-9chum \
      --env-file "${RUNTIME_ENV}" \
      --file "${compose_file}" \
      "$@"
}

verify_image_revision() {
  local image="$1"
  local expected_sha="$2"
  local revision

  revision="$(docker image inspect \
    --format '{{ index .Config.Labels "org.opencontainers.image.revision" }}' \
    "${image}")"
  [[ ${revision} == "${expected_sha}" ]] \
    || fail "Image revision label does not match the requested release."
}

wait_for_url() {
  local url="$1"
  local attempts="${2:-40}"
  local delay_seconds="${3:-3}"
  local attempt

  for ((attempt = 1; attempt <= attempts; attempt += 1)); do
    if curl --fail --silent --show-error --max-time 5 "${url}" >/dev/null 2>&1; then
      return 0
    fi
    sleep "${delay_seconds}"
  done

  return 1
}

rollback_app() {
  local previous_sha="${1:-}"
  local previous_compose="${RELEASES_DIR}/${previous_sha}/compose.production.yml"

  if is_valid_sha "${previous_sha}" \
    && [[ ${previous_sha} != "${RELEASE_SHA}" ]] \
    && [[ -f ${previous_compose} ]]; then
    log "Rolling the app back to ${previous_sha}; database migrations are not rolled back."
    docker pull "${IMAGE_REPOSITORY}:app-${previous_sha}" >/dev/null
    verify_image_revision "${IMAGE_REPOSITORY}:app-${previous_sha}" "${previous_sha}"
    compose_previous "${previous_sha}" "${previous_compose}" up -d --no-deps app
    wait_for_url "http://127.0.0.1:${APP_PORT}/api/health" 40 3 \
      || fail "Rollback app did not become healthy; manual recovery is required."
    return
  fi

  log "No usable previous app release exists; stopping the unhealthy first release."
  compose stop app || true
}

# shellcheck disable=SC1090
source "${BACKUP_FUNCTIONS}"

previous_sha=""
if [[ -f ${CURRENT_SHA_FILE} ]]; then
  previous_sha="$(<"${CURRENT_SHA_FILE}")"
  is_valid_sha "${previous_sha}" || fail "Stored release SHA is invalid."
fi

log "Pulling immutable application image for ${RELEASE_SHA}."
docker pull "${IMAGE_REPOSITORY}:app-${RELEASE_SHA}" >/dev/null
verify_image_revision "${IMAGE_REPOSITORY}:app-${RELEASE_SHA}" "${RELEASE_SHA}"
verify_image_revision "${IMAGE_REPOSITORY}:ops-${RELEASE_SHA}" "${RELEASE_SHA}"
compose --profile ops config --quiet

database_was_running=false
if [[ -n $(compose ps --status running --quiet db 2>/dev/null) ]]; then
  database_was_running=true
  log "Backing up the running database before any Compose reconciliation."
  create_verified_backup "pre-migration-${RELEASE_SHA}"
fi

log "Starting the digest-pinned PostgreSQL service and waiting for its health check."
compose up -d --wait --wait-timeout 120 db

if [[ ${database_was_running} == false ]]; then
  create_verified_backup "pre-migration-${RELEASE_SHA}"
fi

log "Applying Prisma migrations as the restricted migration owner."
compose --profile ops run --rm --no-deps ops \
  ./node_modules/.bin/prisma migrate deploy

log "Updating the application container."
if ! compose up -d --no-deps app; then
  rollback_app "${previous_sha}"
  fail "Application update failed."
fi

if ! wait_for_url "http://127.0.0.1:${APP_PORT}/api/health" 40 3; then
  rollback_app "${previous_sha}"
  fail "Application health check failed."
fi

if ! wait_for_url "${SMOKE_URL}" 10 6; then
  rollback_app "${previous_sha}"
  fail "HTTPS smoke test failed."
fi

# Promote operator assets only after the new app passes both health checks.
install -d -m 0755 -o root -g root \
  "${INSTALL_DIR}/postgres" "${OPERATOR_SBIN_DIR}" "${OPERATOR_LIBEXEC_DIR}"
install -m 0755 -o root -g root \
  "${BUNDLE_DIR}/deploy/postgres/init-app.sh" \
  "${INSTALL_DIR}/postgres/init-app.sh"
install -m 0644 -o root -g root \
  "${SIGNATURE_SQL}" \
  "${INSTALL_DIR}/postgres/backup-signature.sql"
install -m 0644 -o root -g root \
  "${BACKUP_FUNCTIONS}" \
  "${OPERATOR_LIBEXEC_DIR}/donhang-backup-functions"
install -m 0755 -o root -g root "${SCRIPT_DIR}/backup.sh" "${OPERATOR_SBIN_DIR}/donhang-backup"
install -m 0755 -o root -g root "${SCRIPT_DIR}/seed-admin.sh" "${OPERATOR_SBIN_DIR}/donhang-seed-admin"
install -m 0755 -o root -g root "${SCRIPT_DIR}/verify-restore.sh" "${OPERATOR_SBIN_DIR}/donhang-verify-restore"
install -m 0755 -o root -g root "${SCRIPT_DIR}/forced-command.sh" "${OPERATOR_SBIN_DIR}/donhang-deploy-gateway"
install -m 0755 -o root -g root "${SCRIPT_DIR}/release-launcher.sh" "${OPERATOR_SBIN_DIR}/donhang-release"

temporary_link="${INSTALL_DIR}/.current-${RELEASE_SHA}"
rm -f -- "${temporary_link}"
ln -s "releases/${RELEASE_SHA}" "${temporary_link}"
mv -Tf "${temporary_link}" "${CURRENT_BUNDLE_LINK}"

temporary_state="${CURRENT_SHA_FILE}.tmp"
printf '%s\n' "${RELEASE_SHA}" >"${temporary_state}"
chmod 0600 "${temporary_state}"
mv "${temporary_state}" "${CURRENT_SHA_FILE}"

log "Release ${RELEASE_SHA} completed successfully."
